name: DeerlingBot
version: @version@
main: cn.lunadeer.mc.deerlingbot.DeerlingBot
api-version: '1.20'
folia-supported: true
libraries: [ ]
commands:
  deerling:
    description: Main command for DeerlingBot
    usage: /deerling <subcommand>
    permission-message: You do not have permission to use this command.

permissions:
  deerling.command.admin:
    description: Admin permission for DeerlingBot
    default: op
  deerling.command.user:
    description: User permission for DeerlingBot
    default: true